<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>RBS</string>
  <key>fileTypes</key>
  <array>
    <string>rbs</string>
  </array>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#comments</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#keywords</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#strings</string>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>comments</key>
    <dict>
      <key>begin</key>
      <string>#</string>
      <key>end</key>
      <string>
</string>
      <key>name</key>
      <string>comment.line.number-sign</string>
    </dict>
    <key>keywords</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.class.rbs</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.class</string>
            </dict>
          </dict>
          <key>match</key>
          <string>\b(class)\s+([A-Z][a-zA-Z]*)</string>
          <key>name</key>
          <string>keyword.control.class.rbs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(type)\b</string>
          <key>name</key>
          <string>keyword.control.type.rbs</string>
        </dict>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.def.rbs</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.rbs</string>
            </dict>
          </dict>
          <key>match</key>
          <string>\b(def)\b([^:]+)</string>
          <key>name</key>
          <string>keyword.control.def.rbs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(self)\b</string>
          <key>name</key>
          <string>keyword.control.self.rbs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(void)\b</string>
          <key>name</key>
          <string>keyword.control.void.rbs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(any)\b</string>
          <key>name</key>
          <string>keyword.control.any.rbs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(untyped)\b</string>
          <key>name</key>
          <string>keyword.control.untyped.rbs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(top)\b</string>
          <key>name</key>
          <string>keyword.control.top.rbs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(bot)\b</string>
          <key>name</key>
          <string>keyword.control.bot.rbs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(instance)\b</string>
          <key>name</key>
          <string>keyword.control.instance.rbs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(bool)\b</string>
          <key>name</key>
          <string>keyword.control.bool.rbs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(nil)\b</string>
          <key>name</key>
          <string>keyword.control.nil.rbs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(singleton)\b</string>
          <key>name</key>
          <string>keyword.control.singleton.rbs</string>
        </dict>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.interface.rbs</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.class</string>
            </dict>
          </dict>
          <key>match</key>
          <string>\b(interface)\s(_[a-zA-Z]*)</string>
          <key>name</key>
          <string>keyword.control.interface.rbs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(end)\b</string>
          <key>name</key>
          <string>keyword.control.end.rbs</string>
        </dict>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.include.rbs</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.other.constant.rbs</string>
            </dict>
          </dict>
          <key>match</key>
          <string>\b(include)\s([A-Z][a-zA-Z]*)</string>
          <key>name</key>
          <string>keyword.control.include.rbs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(extend)\b</string>
          <key>name</key>
          <string>keyword.control.extend.rbs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(prepend)\b</string>
          <key>name</key>
          <string>keyword.control.prepend.rbs</string>
        </dict>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.module.rbs</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.class</string>
            </dict>
          </dict>
          <key>match</key>
          <string>\b(module)\s+([A-Z][a-zA-Z]*)</string>
          <key>name</key>
          <string>keyword.control.module.rbs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(attr_reader)\b</string>
          <key>name</key>
          <string>keyword.control.attr_reader.rbs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(attr_writer)\b</string>
          <key>name</key>
          <string>keyword.control.attr_writer.rbs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(attr_accessor)\b</string>
          <key>name</key>
          <string>keyword.control.attr_accessor.rbs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(super)\b</string>
          <key>name</key>
          <string>keyword.control.super.rbs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(public)\b</string>
          <key>name</key>
          <string>keyword.control.public.rbs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(private)\b</string>
          <key>name</key>
          <string>keyword.control.private.rbs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(alias)\b</string>
          <key>name</key>
          <string>keyword.control.alias.rbs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(extension)\b</string>
          <key>name</key>
          <string>keyword.control.extension.rbs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(incompatible)\b</string>
          <key>name</key>
          <string>keyword.control.incompatible.rbs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(unchecked)\b</string>
          <key>name</key>
          <string>keyword.control.unchecked.rbs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(out)\b</string>
          <key>name</key>
          <string>keyword.control.out.rbs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(in)\b</string>
          <key>name</key>
          <string>keyword.control.in.rbs</string>
        </dict>
      </array>
    </dict>
    <key>strings</key>
    <dict>
      <key>begin</key>
      <string>"</string>
      <key>end</key>
      <string>"</string>
      <key>name</key>
      <string>string.quoted.double.rbs</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\\.</string>
          <key>name</key>
          <string>constant.character.escape.rbs</string>
        </dict>
      </array>
    </dict>
  </dict>
  <key>scopeName</key>
  <string>source.rbs</string>
</dict>
</plist>
